--Daniel Alexander 2440006715
--Jeremy Andrew Jayaseputra 2440007075
--Kevin Tjandra Wijaya 2440008102
--Virgilius Karel 2440008140

CREATE DATABASE SaraviaPen

USE SaraviaPen

--Customer
CREATE TABLE Customer(
    CustomerID CHAR(6) PRIMARY KEY NOT NULL CHECK(CustomerID like 'CTR[0-9][0-9][0-9]'),
	CustomerName VARCHAR(200)  NOT NULL,
	CustomerGender VARCHAR(20)  NOT NULL,
	CustomerBirth DATE NOT NULL,
	CustomerPhone VARCHAR(12) NOT NULL CHECK(CustomerPhone like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CustomerAddress VARCHAR(200)  NOT NULL
)

--Staff
CREATE TABLE Staff(
    StaffID CHAR(6) PRIMARY KEY NOT NULL CHECK(StaffID like 'STF[0-9][0-9][0-9]'),
	StaffName VARCHAR(200)  NOT NULL CHECK(LEN(StaffName) >= 3),
	StaffGender VARCHAR(20)  NOT NULL CHECK(StaffGender like 'Male' OR StaffGender like 'Female') ,
	StaffBirth DATE NOT NULL,
	StaffPhone VARCHAR(20) NOT NULL,
	StaffAddress VARCHAR(200)  NOT NULL,
	StaffSalary INT NOT NULL
)

--Pen
CREATE TABLE Pen(
	PenID CHAR(6) PRIMARY KEY NOT NULL CHECK(PenID like 'PEN[0-9][0-9][0-9]'),
	PenName VARCHAR(200)  NOT NULL CHECK(PenName like '% Pen'),
	PenPrice INT NOT NULL CHECK(PenPrice BETWEEN 10000 AND 50000),
	PenStock INT NOT NULL
)

--Sales
CREATE TABLE SalesHeader(
    SalesID CHAR(6) PRIMARY KEY NOT NULL CHECK(SalesID like 'SLT[0-9][0-9][0-9]'),
    CustomerID CHAR(6) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	StaffID CHAR(6) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TransactionDate DATE NOT NULL CHECK(YEAR(TransactionDate) LIKE '2020'),
	PaymentType VARCHAR(20) NOT NULL
)
CREATE TABLE SalesDetail(
    SalesID CHAR(6) FOREIGN KEY REFERENCES SalesHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenID CHAR(6) FOREIGN KEY REFERENCES Pen(PenID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenQuantity INT NOT NULL,
	CONSTRAINT SalesKey PRIMARY KEY(SalesID, PenID)
)

--PenMaterial
CREATE TABLE PenMaterial(
	PenMatsID CHAR(6) PRIMARY KEY NOT NULL CHECK(PenMatsID like 'PML[0-9][0-9][0-9]'),
	PenID CHAR(6) FOREIGN KEY REFERENCES Pen(PenID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenMatsName VARCHAR(200) NOT NULL,
	PenMatsPrice INT NOT NULL,
	PenMatsStock INT NOT NULL CHECK(PenMatsStock >= 100)
)

--Vendor
CREATE TABLE Vendor(
    VendorID CHAR(6) PRIMARY KEY NOT NULL CHECK(VendorID like 'VDR[0-9][0-9][0-9]'),
	VendorName VARCHAR(200)  NOT NULL,
	VendorAddress VARCHAR(200)  NOT NULL,
	VendorPhone VARCHAR(20) NOT NULL,
	VendorEmail VARCHAR(200) NOT NULL CHECK(VendorEmail like '%@%')
)

--Purchase
CREATE TABLE PurchaseHeader(
    PurchaseID CHAR(6) PRIMARY KEY NOT NULL CHECK(PurchaseID like 'PCT[0-9][0-9][0-9]'),
    StaffID CHAR(6) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	VendorID CHAR(6) FOREIGN KEY REFERENCES Vendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TransactionDate DATE NOT NULL,
	PaymentType VARCHAR(20) NOT NULL
)
CREATE TABLE PurchaseDetail(
    PurchaseID CHAR(6) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenMatsID CHAR(6) FOREIGN KEY REFERENCES PenMaterial(PenMatsID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenMatsQuantity INT NOT NULL,
	CONSTRAINT PurchaseKey PRIMARY KEY(PurchaseID, PenMatsID)
)